title: Zyrolog
description: Zyrolog - Blog chém gió những câu chuyện xung quanh công việc lập trình của cá nhân mình - Chia sẻ góc nhìn của bản thân về cuộc sống, công việc lập trình cho cộng đồng
author: Đào Xuân Trường
github: https://github.com/tdao7
about: Tôi là Trường - coder mới vào nghề cách đây không lâu. Với tôi chia sẻ kiến thức là cách học tập hiệu quả nhất. Zyrolog là blog chia sẻ những kiến thức lập trình, chuyện linh tinh xoay quanh công việc code dạo... Chia sẻ góc nhìn của bản thân về cuộc sống, công việc lập trình cho cộng đồng...
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/nhatkycoder"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/tdao7/"
    - icon: fa-github
      link: "https://github.com/tdao7"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
#    - text: My Projects
#      url: /projects/
#    - text: XML Feed
#      url: /feed.xml

url: "tdao7.github.io"
baseurl: "blogcodedao"
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
